# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: main

on:
  pull_request:
    types: [opened, reopened, closed, synchronize]

jobs:
  trigger_tests:
    uses: gdrplatform/gDRstyle/.github/workflows/main.yml@main
    with:
      USERNAME: ${{ github.actor }}
      PACKAGE_NAME: ${{ github.event.repository.name }}
      BRANCH_NAME: ${{ github.head_ref }}
      COMMIT_HASH: ${{ github.sha }}
      COMMIT_MSG: ${{ github.event.head_commit.message }}
    secrets: inherit
  trigger_bioc_sync:
    uses: gdrplatform/gDRstyle/.github/workflows/bioc-sync.yaml@main
    with:
      PACKAGE_NAME: ${{ github.event.repository.name }}
    secrets: inherit
